services:
  inventory-service:
    build: .
    ports:
      - "3000:3000"
    networks:
      - inventory-network

  inventory-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge
